/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVoiceGeneratorRouteImport } from './routes/_app.voice-generator'
import { Route as AppVideoStudioRouteImport } from './routes/_app.video-studio'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppStoryboardRouteImport } from './routes/_app.storyboard'
import { Route as AppStoryGeneratorRouteImport } from './routes/_app.story-generator'
import { Route as AppSongsRouteImport } from './routes/_app.songs'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSeoStudioRouteImport } from './routes/_app.seo-studio'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppQueueRouteImport } from './routes/_app.queue'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppMediaStudioRouteImport } from './routes/_app.media-studio'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppImagePromptsRouteImport } from './routes/_app.image-prompts'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCharactersRouteImport } from './routes/_app.characters'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as AppAiProvidersRouteImport } from './routes/_app.ai-providers'
import { Route as AppAiAgentsRouteImport } from './routes/_app.ai-agents'
import { Route as AppProjectsNewRouteImport } from './routes/_app.projects.new'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppProjectSettingsIdRouteImport } from './routes/_app.project-settings.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceGeneratorRoute = AppVoiceGeneratorRouteImport.update({
  id: '/voice-generator',
  path: '/voice-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoStudioRoute = AppVideoStudioRouteImport.update({
  id: '/video-studio',
  path: '/video-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppStoryboardRoute = AppStoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => AppRoute,
} as any)
const AppStoryGeneratorRoute = AppStoryGeneratorRouteImport.update({
  id: '/story-generator',
  path: '/story-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppSongsRoute = AppSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoStudioRoute = AppSeoStudioRouteImport.update({
  id: '/seo-studio',
  path: '/seo-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaStudioRoute = AppMediaStudioRouteImport.update({
  id: '/media-studio',
  path: '/media-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppImagePromptsRoute = AppImagePromptsRouteImport.update({
  id: '/image-prompts',
  path: '/image-prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCharactersRoute = AppCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAiProvidersRoute = AppAiProvidersRouteImport.update({
  id: '/ai-providers',
  path: '/ai-providers',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAgentsRoute = AppAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectSettingsIdRoute = AppProjectSettingsIdRouteImport.update({
  id: '/project-settings/$id',
  path: '/project-settings/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai-agents': typeof AppAiAgentsRoute
  '/ai-providers': typeof AppAiProvidersRoute
  '/assets': typeof AppAssetsRoute
  '/characters': typeof AppCharactersRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/help': typeof AppHelpRoute
  '/history': typeof AppHistoryRoute
  '/image-prompts': typeof AppImagePromptsRoute
  '/import': typeof AppImportRoute
  '/jobs': typeof AppJobsRoute
  '/media-studio': typeof AppMediaStudioRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/queue': typeof AppQueueRoute
  '/search': typeof AppSearchRoute
  '/seo-studio': typeof AppSeoStudioRoute
  '/settings': typeof AppSettingsRoute
  '/songs': typeof AppSongsRoute
  '/story-generator': typeof AppStoryGeneratorRoute
  '/storyboard': typeof AppStoryboardRoute
  '/templates': typeof AppTemplatesRoute
  '/timeline': typeof AppTimelineRoute
  '/video-studio': typeof AppVideoStudioRoute
  '/voice-generator': typeof AppVoiceGeneratorRoute
  '/project-settings/$id': typeof AppProjectSettingsIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/projects/new': typeof AppProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai-agents': typeof AppAiAgentsRoute
  '/ai-providers': typeof AppAiProvidersRoute
  '/assets': typeof AppAssetsRoute
  '/characters': typeof AppCharactersRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/help': typeof AppHelpRoute
  '/history': typeof AppHistoryRoute
  '/image-prompts': typeof AppImagePromptsRoute
  '/import': typeof AppImportRoute
  '/jobs': typeof AppJobsRoute
  '/media-studio': typeof AppMediaStudioRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/queue': typeof AppQueueRoute
  '/search': typeof AppSearchRoute
  '/seo-studio': typeof AppSeoStudioRoute
  '/settings': typeof AppSettingsRoute
  '/songs': typeof AppSongsRoute
  '/story-generator': typeof AppStoryGeneratorRoute
  '/storyboard': typeof AppStoryboardRoute
  '/templates': typeof AppTemplatesRoute
  '/timeline': typeof AppTimelineRoute
  '/video-studio': typeof AppVideoStudioRoute
  '/voice-generator': typeof AppVoiceGeneratorRoute
  '/project-settings/$id': typeof AppProjectSettingsIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/projects/new': typeof AppProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/ai-agents': typeof AppAiAgentsRoute
  '/_app/ai-providers': typeof AppAiProvidersRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/characters': typeof AppCharactersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/export': typeof AppExportRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/image-prompts': typeof AppImagePromptsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/media-studio': typeof AppMediaStudioRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/queue': typeof AppQueueRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/seo-studio': typeof AppSeoStudioRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/songs': typeof AppSongsRoute
  '/_app/story-generator': typeof AppStoryGeneratorRoute
  '/_app/storyboard': typeof AppStoryboardRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/video-studio': typeof AppVideoStudioRoute
  '/_app/voice-generator': typeof AppVoiceGeneratorRoute
  '/_app/project-settings/$id': typeof AppProjectSettingsIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai-agents'
    | '/ai-providers'
    | '/assets'
    | '/characters'
    | '/dashboard'
    | '/export'
    | '/help'
    | '/history'
    | '/image-prompts'
    | '/import'
    | '/jobs'
    | '/media-studio'
    | '/projects'
    | '/queue'
    | '/search'
    | '/seo-studio'
    | '/settings'
    | '/songs'
    | '/story-generator'
    | '/storyboard'
    | '/templates'
    | '/timeline'
    | '/video-studio'
    | '/voice-generator'
    | '/project-settings/$id'
    | '/projects/$id'
    | '/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai-agents'
    | '/ai-providers'
    | '/assets'
    | '/characters'
    | '/dashboard'
    | '/export'
    | '/help'
    | '/history'
    | '/image-prompts'
    | '/import'
    | '/jobs'
    | '/media-studio'
    | '/projects'
    | '/queue'
    | '/search'
    | '/seo-studio'
    | '/settings'
    | '/songs'
    | '/story-generator'
    | '/storyboard'
    | '/templates'
    | '/timeline'
    | '/video-studio'
    | '/voice-generator'
    | '/project-settings/$id'
    | '/projects/$id'
    | '/projects/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/ai-agents'
    | '/_app/ai-providers'
    | '/_app/assets'
    | '/_app/characters'
    | '/_app/dashboard'
    | '/_app/export'
    | '/_app/help'
    | '/_app/history'
    | '/_app/image-prompts'
    | '/_app/import'
    | '/_app/jobs'
    | '/_app/media-studio'
    | '/_app/projects'
    | '/_app/queue'
    | '/_app/search'
    | '/_app/seo-studio'
    | '/_app/settings'
    | '/_app/songs'
    | '/_app/story-generator'
    | '/_app/storyboard'
    | '/_app/templates'
    | '/_app/timeline'
    | '/_app/video-studio'
    | '/_app/voice-generator'
    | '/_app/project-settings/$id'
    | '/_app/projects/$id'
    | '/_app/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/voice-generator': {
      id: '/_app/voice-generator'
      path: '/voice-generator'
      fullPath: '/voice-generator'
      preLoaderRoute: typeof AppVoiceGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/video-studio': {
      id: '/_app/video-studio'
      path: '/video-studio'
      fullPath: '/video-studio'
      preLoaderRoute: typeof AppVideoStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storyboard': {
      id: '/_app/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof AppStoryboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/story-generator': {
      id: '/_app/story-generator'
      path: '/story-generator'
      fullPath: '/story-generator'
      preLoaderRoute: typeof AppStoryGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/songs': {
      id: '/_app/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof AppSongsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seo-studio': {
      id: '/_app/seo-studio'
      path: '/seo-studio'
      fullPath: '/seo-studio'
      preLoaderRoute: typeof AppSeoStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media-studio': {
      id: '/_app/media-studio'
      path: '/media-studio'
      fullPath: '/media-studio'
      preLoaderRoute: typeof AppMediaStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/image-prompts': {
      id: '/_app/image-prompts'
      path: '/image-prompts'
      fullPath: '/image-prompts'
      preLoaderRoute: typeof AppImagePromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/characters': {
      id: '/_app/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof AppCharactersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-providers': {
      id: '/_app/ai-providers'
      path: '/ai-providers'
      fullPath: '/ai-providers'
      preLoaderRoute: typeof AppAiProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-agents': {
      id: '/_app/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AppAiAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/project-settings/$id': {
      id: '/_app/project-settings/$id'
      path: '/project-settings/$id'
      fullPath: '/project-settings/$id'
      preLoaderRoute: typeof AppProjectSettingsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAiAgentsRoute: typeof AppAiAgentsRoute
  AppAiProvidersRoute: typeof AppAiProvidersRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppCharactersRoute: typeof AppCharactersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportRoute: typeof AppExportRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppImagePromptsRoute: typeof AppImagePromptsRoute
  AppImportRoute: typeof AppImportRoute
  AppJobsRoute: typeof AppJobsRoute
  AppMediaStudioRoute: typeof AppMediaStudioRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppQueueRoute: typeof AppQueueRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSeoStudioRoute: typeof AppSeoStudioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSongsRoute: typeof AppSongsRoute
  AppStoryGeneratorRoute: typeof AppStoryGeneratorRoute
  AppStoryboardRoute: typeof AppStoryboardRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppVideoStudioRoute: typeof AppVideoStudioRoute
  AppVoiceGeneratorRoute: typeof AppVoiceGeneratorRoute
  AppProjectSettingsIdRoute: typeof AppProjectSettingsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAgentsRoute: AppAiAgentsRoute,
  AppAiProvidersRoute: AppAiProvidersRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppCharactersRoute: AppCharactersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExportRoute: AppExportRoute,
  AppHelpRoute: AppHelpRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppImagePromptsRoute: AppImagePromptsRoute,
  AppImportRoute: AppImportRoute,
  AppJobsRoute: AppJobsRoute,
  AppMediaStudioRoute: AppMediaStudioRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppQueueRoute: AppQueueRoute,
  AppSearchRoute: AppSearchRoute,
  AppSeoStudioRoute: AppSeoStudioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSongsRoute: AppSongsRoute,
  AppStoryGeneratorRoute: AppStoryGeneratorRoute,
  AppStoryboardRoute: AppStoryboardRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppVideoStudioRoute: AppVideoStudioRoute,
  AppVoiceGeneratorRoute: AppVoiceGeneratorRoute,
  AppProjectSettingsIdRoute: AppProjectSettingsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
